# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test NextflowEventModel")

model.instance <- NextflowEventModel$new()

test_that("runName", {
  # tests for the property `runName` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`runName`, "EXPECTED_RESULT")
})

test_that("runId", {
  # tests for the property `runId` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`runId`, "EXPECTED_RESULT")
})

test_that("event", {
  # tests for the property `event` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`event`, "EXPECTED_RESULT")
})

test_that("utcTime", {
  # tests for the property `utcTime` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`utcTime`, "EXPECTED_RESULT")
})

test_that("trace", {
  # tests for the property `trace` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`trace`, "EXPECTED_RESULT")
})

test_that("metadata", {
  # tests for the property `metadata` (object)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metadata`, "EXPECTED_RESULT")
})

