# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DefaultApi")

api.instance <- DefaultApi$new()

test_that("AddNextflowEventNextflowEventsPost", {
  # tests for AddNextflowEventNextflowEventsPost
  # base path: http://localhost
  # Add Nextflow Event
  # Events from running Nextflow pipelines when using -with-weblog.  See [the Nextflow documentation](https://www.nextflow.io/docs/latest/tracing.html#weblog-via-http).
  # @param nextflow.event.model NextflowEventModel 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("AddUserUsersPost", {
  # tests for AddUserUsersPost
  # base path: http://localhost
  # Add User
  # @param user.model UserModel 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteUserUsersUidDelete", {
  # tests for DeleteUserUsersUidDelete
  # base path: http://localhost
  # Delete User
  # @param uid integer 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("FilesChangeFilesChangesPost", {
  # tests for FilesChangeFilesChangesPost
  # base path: http://localhost
  # Files Change
  # Track all changes in cloud storage
  # @param body object 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GenerateDownloadSignedUrlV4FilesSignedGet", {
  # tests for GenerateDownloadSignedUrlV4FilesSignedGet
  # base path: http://localhost
  # Generate Download Signed Url V4
  # Generates a v4 signed URL for downloading a blob.  Note that this method requires a service account key file. You can not use this if you are using Application Default Credentials from Google Compute Engine or from the Google Cloud SDK.
  # @param name character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetNextflowEventNextflowEventsIdGet", {
  # tests for GetNextflowEventNextflowEventsIdGet
  # base path: http://localhost
  # Get Nextflow Event
  # @param id character 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetUserUsersUidGet", {
  # tests for GetUserUsersUidGet
  # base path: http://localhost
  # Get User
  # @param uid integer 
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListFileEventsFilesChangesGet", {
  # tests for ListFileEventsFilesChangesGet
  # base path: http://localhost
  # List File Events
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @param start.date character  (optional)
  # @param end.date character  (optional)
  # @param filename.regex character  (optional)
  # @return [StorageEventCollection]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListNextflowEventsNextflowEventsGet", {
  # tests for ListNextflowEventsNextflowEventsGet
  # base path: http://localhost
  # List Nextflow Events
  # @param limit integer  (optional)
  # @param offset integer  (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("ListUsersUsersGet", {
  # tests for ListUsersUsersGet
  # base path: http://localhost
  # List Users
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

