# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StorageEventReturn")

model.instance <- StorageEventReturn$new()

test_that("kind", {
  # tests for the property `kind` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`kind`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("selfLink", {
  # tests for the property `selfLink` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`selfLink`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("bucket", {
  # tests for the property `bucket` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`bucket`, "EXPECTED_RESULT")
})

test_that("generation", {
  # tests for the property `generation` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`generation`, "EXPECTED_RESULT")
})

test_that("metageneration", {
  # tests for the property `metageneration` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`metageneration`, "EXPECTED_RESULT")
})

test_that("contentType", {
  # tests for the property `contentType` (character)
  # The MIME type of the object

  # uncomment below to test the property 
  #expect_equal(model.instance$`contentType`, "EXPECTED_RESULT")
})

test_that("timeCreated", {
  # tests for the property `timeCreated` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`timeCreated`, "EXPECTED_RESULT")
})

test_that("updated", {
  # tests for the property `updated` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`updated`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)

  # uncomment below to test the property 
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("md5Hash", {
  # tests for the property `md5Hash` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`md5Hash`, "EXPECTED_RESULT")
})

test_that("mediaLink", {
  # tests for the property `mediaLink` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`mediaLink`, "EXPECTED_RESULT")
})

test_that("contentLanguage", {
  # tests for the property `contentLanguage` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`contentLanguage`, "EXPECTED_RESULT")
})

test_that("crc32c", {
  # tests for the property `crc32c` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`crc32c`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

test_that("eventType", {
  # tests for the property `eventType` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`eventType`, "EXPECTED_RESULT")
})

test_that("eventTime", {
  # tests for the property `eventTime` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`eventTime`, "EXPECTED_RESULT")
})

test_that("event_id", {
  # tests for the property `event_id` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`event_id`, "EXPECTED_RESULT")
})

test_that("download_url", {
  # tests for the property `download_url` (character)

  # uncomment below to test the property 
  #expect_equal(model.instance$`download_url`, "EXPECTED_RESULT")
})

