# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StorageEventCollection")

model.instance <- StorageEventCollection$new()

test_that("hits", {
  # tests for the property `hits` (array[StorageEventReturn])

  # uncomment below to test the property 
  #expect_equal(model.instance$`hits`, "EXPECTED_RESULT")
})

