# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Default operations
#' @description metagenomicsClientR.Default
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ AddNextflowEventNextflowEventsPost } \emph{ Add Nextflow Event }
#' Events from running Nextflow pipelines when using -with-weblog.  See [the Nextflow documentation](https://www.nextflow.io/docs/latest/tracing.html#weblog-via-http).
#'
#' \itemize{
#' \item \emph{ @param } nextflow.event.model \link{NextflowEventModel}
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ AddUserUsersPost } \emph{ Add User }
#' 
#'
#' \itemize{
#' \item \emph{ @param } user.model \link{UserModel}
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteUserUsersUidDelete } \emph{ Delete User }
#' 
#'
#' \itemize{
#' \item \emph{ @param } uid integer
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ FilesChangeFilesChangesPost } \emph{ Files Change }
#' Track all changes in cloud storage
#'
#' \itemize{
#' \item \emph{ @param } body object
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GenerateDownloadSignedUrlV4FilesSignedGet } \emph{ Generate Download Signed Url V4 }
#' Generates a v4 signed URL for downloading a blob.  Note that this method requires a service account key file. You can not use this if you are using Application Default Credentials from Google Compute Engine or from the Google Cloud SDK.
#'
#' \itemize{
#' \item \emph{ @param } name character
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetNextflowEventNextflowEventsIdGet } \emph{ Get Nextflow Event }
#' 
#'
#' \itemize{
#' \item \emph{ @param } id \link{character}
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetUserUsersUidGet } \emph{ Get User }
#' 
#'
#' \itemize{
#' \item \emph{ @param } uid integer
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListFileEventsFilesChangesGet } \emph{ List File Events }
#' 
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @param } start.date character
#' \item \emph{ @param } end.date character
#' \item \emph{ @param } filename.regex character
#' \item \emph{ @returnType } \link{StorageEventCollection} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : StorageEventCollection 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListNextflowEventsNextflowEventsGet } \emph{ List Nextflow Events }
#' 
#'
#' \itemize{
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' \item status code : 422 | Validation Error
#'
#' \item return type : HTTPValidationError 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListUsersUsersGet } \emph{ List Users }
#' 
#'
#' \itemize{
#' \item \emph{ @returnType } \link{AnyType} \cr
#'
#'
#' \item status code : 200 | Successful Response
#'
#' \item return type : AnyType 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  AddNextflowEventNextflowEventsPost  ####################
#'
#' library(metagenomicsClientR)
#' var.nextflow.event.model <- NextflowEventModel$new() # NextflowEventModel | 
#'
#' #Add Nextflow Event
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$AddNextflowEventNextflowEventsPost(var.nextflow.event.model)
#'
#'
#' ####################  AddUserUsersPost  ####################
#'
#' library(metagenomicsClientR)
#' var.user.model <- UserModel$new() # UserModel | 
#'
#' #Add User
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$AddUserUsersPost(var.user.model)
#'
#'
#' ####################  DeleteUserUsersUidDelete  ####################
#'
#' library(metagenomicsClientR)
#' var.uid <- 56 # integer | 
#'
#' #Delete User
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$DeleteUserUsersUidDelete(var.uid)
#'
#'
#' ####################  FilesChangeFilesChangesPost  ####################
#'
#' library(metagenomicsClientR)
#' var.body <- NULL # object | 
#'
#' #Files Change
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$FilesChangeFilesChangesPost(var.body)
#'
#'
#' ####################  GenerateDownloadSignedUrlV4FilesSignedGet  ####################
#'
#' library(metagenomicsClientR)
#' var.name <- 'name_example' # character | 
#'
#' #Generate Download Signed Url V4
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$GenerateDownloadSignedUrlV4FilesSignedGet(var.name)
#'
#'
#' ####################  GetNextflowEventNextflowEventsIdGet  ####################
#'
#' library(metagenomicsClientR)
#' var.id <- 'id_example' # character | 
#'
#' #Get Nextflow Event
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$GetNextflowEventNextflowEventsIdGet(var.id)
#'
#'
#' ####################  GetUserUsersUidGet  ####################
#'
#' library(metagenomicsClientR)
#' var.uid <- 56 # integer | 
#'
#' #Get User
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$GetUserUsersUidGet(var.uid)
#'
#'
#' ####################  ListFileEventsFilesChangesGet  ####################
#'
#' library(metagenomicsClientR)
#' var.limit <- 100 # integer | 
#' var.offset <- 0 # integer | 
#' var.start.date <- 'start.date_example' # character | 
#' var.end.date <- 'end.date_example' # character | 
#' var.filename.regex <- 'filename.regex_example' # character | 
#'
#' #List File Events
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$ListFileEventsFilesChangesGet(limit=var.limit, offset=var.offset, start.date=var.start.date, end.date=var.end.date, filename.regex=var.filename.regex)
#'
#'
#' ####################  ListNextflowEventsNextflowEventsGet  ####################
#'
#' library(metagenomicsClientR)
#' var.limit <- 100 # integer | 
#' var.offset <- 0 # integer | 
#'
#' #List Nextflow Events
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$ListNextflowEventsNextflowEventsGet(limit=var.limit, offset=var.offset)
#'
#'
#' ####################  ListUsersUsersGet  ####################
#'
#' library(metagenomicsClientR)
#'
#' #List Users
#' api.instance <- DefaultApi$new()
#'
#' result <- api.instance$ListUsersUsersGet()
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
DefaultApi <- R6::R6Class(
  'DefaultApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    AddNextflowEventNextflowEventsPost = function(nextflow.event.model, ...){
      apiResponse <- self$AddNextflowEventNextflowEventsPostWithHttpInfo(nextflow.event.model, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    AddNextflowEventNextflowEventsPostWithHttpInfo = function(nextflow.event.model, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`nextflow.event.model`)) {
        stop("Missing required parameter `nextflow.event.model`.")
      }

      if (!missing(`nextflow.event.model`)) {
        body <- `nextflow.event.model`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/nextflow/events"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    AddUserUsersPost = function(user.model, ...){
      apiResponse <- self$AddUserUsersPostWithHttpInfo(user.model, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    AddUserUsersPostWithHttpInfo = function(user.model, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`user.model`)) {
        stop("Missing required parameter `user.model`.")
      }

      if (!missing(`user.model`)) {
        body <- `user.model`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/users"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteUserUsersUidDelete = function(uid, ...){
      apiResponse <- self$DeleteUserUsersUidDeleteWithHttpInfo(uid, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteUserUsersUidDeleteWithHttpInfo = function(uid, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`uid`)) {
        stop("Missing required parameter `uid`.")
      }

      body <- NULL
      urlPath <- "/users/{uid}"
      if (!missing(`uid`)) {
        urlPath <- gsub(paste0("\\{", "uid", "\\}"), URLencode(as.character(`uid`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    FilesChangeFilesChangesPost = function(body, ...){
      apiResponse <- self$FilesChangeFilesChangesPostWithHttpInfo(body, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    FilesChangeFilesChangesPostWithHttpInfo = function(body, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`body`)) {
        stop("Missing required parameter `body`.")
      }

      if (!missing(`body`)) {
        body <- `body`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/files/changes"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GenerateDownloadSignedUrlV4FilesSignedGet = function(name, ...){
      apiResponse <- self$GenerateDownloadSignedUrlV4FilesSignedGetWithHttpInfo(name, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GenerateDownloadSignedUrlV4FilesSignedGetWithHttpInfo = function(name, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`name`)) {
        stop("Missing required parameter `name`.")
      }

      queryParams['name'] <- name

      body <- NULL
      urlPath <- "/files/signed"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetNextflowEventNextflowEventsIdGet = function(id, ...){
      apiResponse <- self$GetNextflowEventNextflowEventsIdGetWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetNextflowEventNextflowEventsIdGetWithHttpInfo = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      body <- NULL
      urlPath <- "/nextflow/events/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetUserUsersUidGet = function(uid, ...){
      apiResponse <- self$GetUserUsersUidGetWithHttpInfo(uid, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetUserUsersUidGetWithHttpInfo = function(uid, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`uid`)) {
        stop("Missing required parameter `uid`.")
      }

      body <- NULL
      urlPath <- "/users/{uid}"
      if (!missing(`uid`)) {
        urlPath <- gsub(paste0("\\{", "uid", "\\}"), URLencode(as.character(`uid`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListFileEventsFilesChangesGet = function(limit=100, offset=0, start.date=NULL, end.date=NULL, filename.regex=NULL, ...){
      apiResponse <- self$ListFileEventsFilesChangesGetWithHttpInfo(limit, offset, start.date, end.date, filename.regex, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListFileEventsFilesChangesGetWithHttpInfo = function(limit=100, offset=0, start.date=NULL, end.date=NULL, filename.regex=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      queryParams['start_date'] <- start.date

      queryParams['end_date'] <- end.date

      queryParams['filename_regex'] <- filename.regex

      body <- NULL
      urlPath <- "/files/changes"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "StorageEventCollection", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListNextflowEventsNextflowEventsGet = function(limit=100, offset=0, ...){
      apiResponse <- self$ListNextflowEventsNextflowEventsGetWithHttpInfo(limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListNextflowEventsNextflowEventsGetWithHttpInfo = function(limit=100, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      body <- NULL
      urlPath <- "/nextflow/events"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListUsersUsersGet = function(...){
      apiResponse <- self$ListUsersUsersGetWithHttpInfo(...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListUsersUsersGetWithHttpInfo = function(...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      body <- NULL
      urlPath <- "/users"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AnyType", loadNamespace("metagenomicsClientR")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
