# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title NextflowEventModel
#'
#' @description NextflowEventModel Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field runName Runname character 
#'
#' @field runId Runid character 
#'
#' @field event Event character 
#'
#' @field utcTime Utctime character 
#'
#' @field trace Trace object [optional]
#'
#' @field metadata Metadata object [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NextflowEventModel <- R6::R6Class(
  'NextflowEventModel',
  public = list(
    `runName` = NULL,
    `runId` = NULL,
    `event` = NULL,
    `utcTime` = NULL,
    `trace` = NULL,
    `metadata` = NULL,
    initialize = function(
        `runName`, `runId`, `event`, `utcTime`, `trace`=NULL, `metadata`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`runName`)) {
        stopifnot(is.character(`runName`), length(`runName`) == 1)
        self$`runName` <- `runName`
      }
      if (!missing(`runId`)) {
        stopifnot(is.character(`runId`), length(`runId`) == 1)
        self$`runId` <- `runId`
      }
      if (!missing(`event`)) {
        stopifnot(is.character(`event`), length(`event`) == 1)
        self$`event` <- `event`
      }
      if (!missing(`utcTime`)) {
        stopifnot(is.character(`utcTime`), length(`utcTime`) == 1)
        self$`utcTime` <- `utcTime`
      }
      if (!is.null(`trace`)) {
        self$`trace` <- `trace`
      }
      if (!is.null(`metadata`)) {
        self$`metadata` <- `metadata`
      }
    },
    toJSON = function() {
      NextflowEventModelObject <- list()
      if (!is.null(self$`runName`)) {
        NextflowEventModelObject[['runName']] <-
          self$`runName`
      }
      if (!is.null(self$`runId`)) {
        NextflowEventModelObject[['runId']] <-
          self$`runId`
      }
      if (!is.null(self$`event`)) {
        NextflowEventModelObject[['event']] <-
          self$`event`
      }
      if (!is.null(self$`utcTime`)) {
        NextflowEventModelObject[['utcTime']] <-
          self$`utcTime`
      }
      if (!is.null(self$`trace`)) {
        NextflowEventModelObject[['trace']] <-
          self$`trace`
      }
      if (!is.null(self$`metadata`)) {
        NextflowEventModelObject[['metadata']] <-
          self$`metadata`
      }

      NextflowEventModelObject
    },
    fromJSON = function(NextflowEventModelJson) {
      NextflowEventModelObject <- jsonlite::fromJSON(NextflowEventModelJson)
      if (!is.null(NextflowEventModelObject$`runName`)) {
        self$`runName` <- NextflowEventModelObject$`runName`
      }
      if (!is.null(NextflowEventModelObject$`runId`)) {
        self$`runId` <- NextflowEventModelObject$`runId`
      }
      if (!is.null(NextflowEventModelObject$`event`)) {
        self$`event` <- NextflowEventModelObject$`event`
      }
      if (!is.null(NextflowEventModelObject$`utcTime`)) {
        self$`utcTime` <- NextflowEventModelObject$`utcTime`
      }
      if (!is.null(NextflowEventModelObject$`trace`)) {
        self$`trace` <- NextflowEventModelObject$`trace`
      }
      if (!is.null(NextflowEventModelObject$`metadata`)) {
        self$`metadata` <- NextflowEventModelObject$`metadata`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`runName`)) {
        sprintf(
        '"runName":
          "%s"
                ',
        self$`runName`
        )},
        if (!is.null(self$`runId`)) {
        sprintf(
        '"runId":
          "%s"
                ',
        self$`runId`
        )},
        if (!is.null(self$`event`)) {
        sprintf(
        '"event":
          "%s"
                ',
        self$`event`
        )},
        if (!is.null(self$`utcTime`)) {
        sprintf(
        '"utcTime":
          "%s"
                ',
        self$`utcTime`
        )},
        if (!is.null(self$`trace`)) {
        sprintf(
        '"trace":
          "%s"
                ',
        self$`trace`
        )},
        if (!is.null(self$`metadata`)) {
        sprintf(
        '"metadata":
          "%s"
                ',
        self$`metadata`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(NextflowEventModelJson) {
      NextflowEventModelObject <- jsonlite::fromJSON(NextflowEventModelJson)
      self$`runName` <- NextflowEventModelObject$`runName`
      self$`runId` <- NextflowEventModelObject$`runId`
      self$`event` <- NextflowEventModelObject$`event`
      self$`utcTime` <- NextflowEventModelObject$`utcTime`
      self$`trace` <- NextflowEventModelObject$`trace`
      self$`metadata` <- NextflowEventModelObject$`metadata`
      self
    }
  )
)

