# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StorageEventReturn
#'
#' @description StorageEventReturn Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field kind Kind character 
#'
#' @field id Id character 
#'
#' @field selfLink Selflink character 
#'
#' @field name Name character 
#'
#' @field bucket Bucket character 
#'
#' @field generation Generation integer 
#'
#' @field metageneration Metageneration integer 
#'
#' @field contentType Contenttype character 
#'
#' @field timeCreated Timecreated character 
#'
#' @field updated Updated character 
#'
#' @field size Size integer 
#'
#' @field md5Hash Md5Hash character 
#'
#' @field mediaLink Medialink character 
#'
#' @field contentLanguage Contentlanguage character [optional]
#'
#' @field crc32c Crc32C character 
#'
#' @field etag Etag character 
#'
#' @field eventType Eventtype character 
#'
#' @field eventTime Eventtime character 
#'
#' @field event_id Event Id character 
#'
#' @field download_url Download Url character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StorageEventReturn <- R6::R6Class(
  'StorageEventReturn',
  public = list(
    `kind` = NULL,
    `id` = NULL,
    `selfLink` = NULL,
    `name` = NULL,
    `bucket` = NULL,
    `generation` = NULL,
    `metageneration` = NULL,
    `contentType` = NULL,
    `timeCreated` = NULL,
    `updated` = NULL,
    `size` = NULL,
    `md5Hash` = NULL,
    `mediaLink` = NULL,
    `contentLanguage` = NULL,
    `crc32c` = NULL,
    `etag` = NULL,
    `eventType` = NULL,
    `eventTime` = NULL,
    `event_id` = NULL,
    `download_url` = NULL,
    initialize = function(
        `kind`, `id`, `selfLink`, `name`, `bucket`, `generation`, `metageneration`, `contentType`, `timeCreated`, `updated`, `size`, `md5Hash`, `mediaLink`, `crc32c`, `etag`, `eventType`, `eventTime`, `event_id`, `download_url`, `contentLanguage`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`kind`)) {
        stopifnot(is.character(`kind`), length(`kind`) == 1)
        self$`kind` <- `kind`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`selfLink`)) {
        stopifnot(is.character(`selfLink`), length(`selfLink`) == 1)
        self$`selfLink` <- `selfLink`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`bucket`)) {
        stopifnot(is.character(`bucket`), length(`bucket`) == 1)
        self$`bucket` <- `bucket`
      }
      if (!missing(`generation`)) {
        stopifnot(is.numeric(`generation`), length(`generation`) == 1)
        self$`generation` <- `generation`
      }
      if (!missing(`metageneration`)) {
        stopifnot(is.numeric(`metageneration`), length(`metageneration`) == 1)
        self$`metageneration` <- `metageneration`
      }
      if (!missing(`contentType`)) {
        stopifnot(is.character(`contentType`), length(`contentType`) == 1)
        self$`contentType` <- `contentType`
      }
      if (!missing(`timeCreated`)) {
        stopifnot(is.character(`timeCreated`), length(`timeCreated`) == 1)
        self$`timeCreated` <- `timeCreated`
      }
      if (!missing(`updated`)) {
        stopifnot(is.character(`updated`), length(`updated`) == 1)
        self$`updated` <- `updated`
      }
      if (!missing(`size`)) {
        stopifnot(is.numeric(`size`), length(`size`) == 1)
        self$`size` <- `size`
      }
      if (!missing(`md5Hash`)) {
        stopifnot(is.character(`md5Hash`), length(`md5Hash`) == 1)
        self$`md5Hash` <- `md5Hash`
      }
      if (!missing(`mediaLink`)) {
        stopifnot(is.character(`mediaLink`), length(`mediaLink`) == 1)
        self$`mediaLink` <- `mediaLink`
      }
      if (!missing(`crc32c`)) {
        stopifnot(is.character(`crc32c`), length(`crc32c`) == 1)
        self$`crc32c` <- `crc32c`
      }
      if (!missing(`etag`)) {
        stopifnot(is.character(`etag`), length(`etag`) == 1)
        self$`etag` <- `etag`
      }
      if (!missing(`eventType`)) {
        stopifnot(is.character(`eventType`), length(`eventType`) == 1)
        self$`eventType` <- `eventType`
      }
      if (!missing(`eventTime`)) {
        stopifnot(is.character(`eventTime`), length(`eventTime`) == 1)
        self$`eventTime` <- `eventTime`
      }
      if (!missing(`event_id`)) {
        stopifnot(is.character(`event_id`), length(`event_id`) == 1)
        self$`event_id` <- `event_id`
      }
      if (!missing(`download_url`)) {
        stopifnot(is.character(`download_url`), length(`download_url`) == 1)
        self$`download_url` <- `download_url`
      }
      if (!is.null(`contentLanguage`)) {
        stopifnot(is.character(`contentLanguage`), length(`contentLanguage`) == 1)
        self$`contentLanguage` <- `contentLanguage`
      }
    },
    toJSON = function() {
      StorageEventReturnObject <- list()
      if (!is.null(self$`kind`)) {
        StorageEventReturnObject[['kind']] <-
          self$`kind`
      }
      if (!is.null(self$`id`)) {
        StorageEventReturnObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`selfLink`)) {
        StorageEventReturnObject[['selfLink']] <-
          self$`selfLink`
      }
      if (!is.null(self$`name`)) {
        StorageEventReturnObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`bucket`)) {
        StorageEventReturnObject[['bucket']] <-
          self$`bucket`
      }
      if (!is.null(self$`generation`)) {
        StorageEventReturnObject[['generation']] <-
          self$`generation`
      }
      if (!is.null(self$`metageneration`)) {
        StorageEventReturnObject[['metageneration']] <-
          self$`metageneration`
      }
      if (!is.null(self$`contentType`)) {
        StorageEventReturnObject[['contentType']] <-
          self$`contentType`
      }
      if (!is.null(self$`timeCreated`)) {
        StorageEventReturnObject[['timeCreated']] <-
          self$`timeCreated`
      }
      if (!is.null(self$`updated`)) {
        StorageEventReturnObject[['updated']] <-
          self$`updated`
      }
      if (!is.null(self$`size`)) {
        StorageEventReturnObject[['size']] <-
          self$`size`
      }
      if (!is.null(self$`md5Hash`)) {
        StorageEventReturnObject[['md5Hash']] <-
          self$`md5Hash`
      }
      if (!is.null(self$`mediaLink`)) {
        StorageEventReturnObject[['mediaLink']] <-
          self$`mediaLink`
      }
      if (!is.null(self$`contentLanguage`)) {
        StorageEventReturnObject[['contentLanguage']] <-
          self$`contentLanguage`
      }
      if (!is.null(self$`crc32c`)) {
        StorageEventReturnObject[['crc32c']] <-
          self$`crc32c`
      }
      if (!is.null(self$`etag`)) {
        StorageEventReturnObject[['etag']] <-
          self$`etag`
      }
      if (!is.null(self$`eventType`)) {
        StorageEventReturnObject[['eventType']] <-
          self$`eventType`
      }
      if (!is.null(self$`eventTime`)) {
        StorageEventReturnObject[['eventTime']] <-
          self$`eventTime`
      }
      if (!is.null(self$`event_id`)) {
        StorageEventReturnObject[['event_id']] <-
          self$`event_id`
      }
      if (!is.null(self$`download_url`)) {
        StorageEventReturnObject[['download_url']] <-
          self$`download_url`
      }

      StorageEventReturnObject
    },
    fromJSON = function(StorageEventReturnJson) {
      StorageEventReturnObject <- jsonlite::fromJSON(StorageEventReturnJson)
      if (!is.null(StorageEventReturnObject$`kind`)) {
        self$`kind` <- StorageEventReturnObject$`kind`
      }
      if (!is.null(StorageEventReturnObject$`id`)) {
        self$`id` <- StorageEventReturnObject$`id`
      }
      if (!is.null(StorageEventReturnObject$`selfLink`)) {
        self$`selfLink` <- StorageEventReturnObject$`selfLink`
      }
      if (!is.null(StorageEventReturnObject$`name`)) {
        self$`name` <- StorageEventReturnObject$`name`
      }
      if (!is.null(StorageEventReturnObject$`bucket`)) {
        self$`bucket` <- StorageEventReturnObject$`bucket`
      }
      if (!is.null(StorageEventReturnObject$`generation`)) {
        self$`generation` <- StorageEventReturnObject$`generation`
      }
      if (!is.null(StorageEventReturnObject$`metageneration`)) {
        self$`metageneration` <- StorageEventReturnObject$`metageneration`
      }
      if (!is.null(StorageEventReturnObject$`contentType`)) {
        self$`contentType` <- StorageEventReturnObject$`contentType`
      }
      if (!is.null(StorageEventReturnObject$`timeCreated`)) {
        self$`timeCreated` <- StorageEventReturnObject$`timeCreated`
      }
      if (!is.null(StorageEventReturnObject$`updated`)) {
        self$`updated` <- StorageEventReturnObject$`updated`
      }
      if (!is.null(StorageEventReturnObject$`size`)) {
        self$`size` <- StorageEventReturnObject$`size`
      }
      if (!is.null(StorageEventReturnObject$`md5Hash`)) {
        self$`md5Hash` <- StorageEventReturnObject$`md5Hash`
      }
      if (!is.null(StorageEventReturnObject$`mediaLink`)) {
        self$`mediaLink` <- StorageEventReturnObject$`mediaLink`
      }
      if (!is.null(StorageEventReturnObject$`contentLanguage`)) {
        self$`contentLanguage` <- StorageEventReturnObject$`contentLanguage`
      }
      if (!is.null(StorageEventReturnObject$`crc32c`)) {
        self$`crc32c` <- StorageEventReturnObject$`crc32c`
      }
      if (!is.null(StorageEventReturnObject$`etag`)) {
        self$`etag` <- StorageEventReturnObject$`etag`
      }
      if (!is.null(StorageEventReturnObject$`eventType`)) {
        self$`eventType` <- StorageEventReturnObject$`eventType`
      }
      if (!is.null(StorageEventReturnObject$`eventTime`)) {
        self$`eventTime` <- StorageEventReturnObject$`eventTime`
      }
      if (!is.null(StorageEventReturnObject$`event_id`)) {
        self$`event_id` <- StorageEventReturnObject$`event_id`
      }
      if (!is.null(StorageEventReturnObject$`download_url`)) {
        self$`download_url` <- StorageEventReturnObject$`download_url`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`kind`)) {
        sprintf(
        '"kind":
          "%s"
                ',
        self$`kind`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`selfLink`)) {
        sprintf(
        '"selfLink":
          "%s"
                ',
        self$`selfLink`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`bucket`)) {
        sprintf(
        '"bucket":
          "%s"
                ',
        self$`bucket`
        )},
        if (!is.null(self$`generation`)) {
        sprintf(
        '"generation":
          %d
                ',
        self$`generation`
        )},
        if (!is.null(self$`metageneration`)) {
        sprintf(
        '"metageneration":
          %d
                ',
        self$`metageneration`
        )},
        if (!is.null(self$`contentType`)) {
        sprintf(
        '"contentType":
          "%s"
                ',
        self$`contentType`
        )},
        if (!is.null(self$`timeCreated`)) {
        sprintf(
        '"timeCreated":
          "%s"
                ',
        self$`timeCreated`
        )},
        if (!is.null(self$`updated`)) {
        sprintf(
        '"updated":
          "%s"
                ',
        self$`updated`
        )},
        if (!is.null(self$`size`)) {
        sprintf(
        '"size":
          %d
                ',
        self$`size`
        )},
        if (!is.null(self$`md5Hash`)) {
        sprintf(
        '"md5Hash":
          "%s"
                ',
        self$`md5Hash`
        )},
        if (!is.null(self$`mediaLink`)) {
        sprintf(
        '"mediaLink":
          "%s"
                ',
        self$`mediaLink`
        )},
        if (!is.null(self$`contentLanguage`)) {
        sprintf(
        '"contentLanguage":
          "%s"
                ',
        self$`contentLanguage`
        )},
        if (!is.null(self$`crc32c`)) {
        sprintf(
        '"crc32c":
          "%s"
                ',
        self$`crc32c`
        )},
        if (!is.null(self$`etag`)) {
        sprintf(
        '"etag":
          "%s"
                ',
        self$`etag`
        )},
        if (!is.null(self$`eventType`)) {
        sprintf(
        '"eventType":
          "%s"
                ',
        self$`eventType`
        )},
        if (!is.null(self$`eventTime`)) {
        sprintf(
        '"eventTime":
          "%s"
                ',
        self$`eventTime`
        )},
        if (!is.null(self$`event_id`)) {
        sprintf(
        '"event_id":
          "%s"
                ',
        self$`event_id`
        )},
        if (!is.null(self$`download_url`)) {
        sprintf(
        '"download_url":
          "%s"
                ',
        self$`download_url`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StorageEventReturnJson) {
      StorageEventReturnObject <- jsonlite::fromJSON(StorageEventReturnJson)
      self$`kind` <- StorageEventReturnObject$`kind`
      self$`id` <- StorageEventReturnObject$`id`
      self$`selfLink` <- StorageEventReturnObject$`selfLink`
      self$`name` <- StorageEventReturnObject$`name`
      self$`bucket` <- StorageEventReturnObject$`bucket`
      self$`generation` <- StorageEventReturnObject$`generation`
      self$`metageneration` <- StorageEventReturnObject$`metageneration`
      self$`contentType` <- StorageEventReturnObject$`contentType`
      self$`timeCreated` <- StorageEventReturnObject$`timeCreated`
      self$`updated` <- StorageEventReturnObject$`updated`
      self$`size` <- StorageEventReturnObject$`size`
      self$`md5Hash` <- StorageEventReturnObject$`md5Hash`
      self$`mediaLink` <- StorageEventReturnObject$`mediaLink`
      self$`contentLanguage` <- StorageEventReturnObject$`contentLanguage`
      self$`crc32c` <- StorageEventReturnObject$`crc32c`
      self$`etag` <- StorageEventReturnObject$`etag`
      self$`eventType` <- StorageEventReturnObject$`eventType`
      self$`eventTime` <- StorageEventReturnObject$`eventTime`
      self$`event_id` <- StorageEventReturnObject$`event_id`
      self$`download_url` <- StorageEventReturnObject$`download_url`
      self
    }
  )
)

