# Curated Metagenomics Web Portal and API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: 0.1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UserModel
#'
#' @description UserModel Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field name Name character 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserModel <- R6::R6Class(
  'UserModel',
  public = list(
    `name` = NULL,
    initialize = function(
        `name`, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      UserModelObject <- list()
      if (!is.null(self$`name`)) {
        UserModelObject[['name']] <-
          self$`name`
      }

      UserModelObject
    },
    fromJSON = function(UserModelJson) {
      UserModelObject <- jsonlite::fromJSON(UserModelJson)
      if (!is.null(UserModelObject$`name`)) {
        self$`name` <- UserModelObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UserModelJson) {
      UserModelObject <- jsonlite::fromJSON(UserModelJson)
      self$`name` <- UserModelObject$`name`
      self
    }
  )
)

